modelNewApp/urls.py
from django.urls import path
from .views import *

app_name = "modelNewApp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("recuperar_contraseña/", recuperar_contraseña, name="recuperar_contraseña"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('cambiar_password/', cambiar_password, name='cambiar_password'),
    path("control/", control, name="control"),
    path("control/pie", control_pie, name="control_pie"),
    path("control/vehiculo", control_vehiculo, name="control_vehiculo"),
    path("ajax/buscar-vehiculo/", buscar_vehiculo_por_placa, name="buscar_vehiculo"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/personas/", empleados, name="empleados"),
    path("dashboard/personas/agregar", empleados_agregar, name="empleados_agregar"),
    path("dashboard/personas/detalles/<int:id>/", empleados_detalles, name="empleados_detalles"),
    path("dashboard/personas/eliminar/<int:id>/", empleados_eliminar, name="empleados_eliminar"),
    path("dashboard/personas/editar/<int:id>/", empleados_editar, name="empleados_editar"),
    path("dashboard/personas/activar/<int:id>/", empleados_activar, name="empleados_activar"),
    path("dashboard/personas/desactivar/<int:id>/", empleados_desactivar, name="empleados_desactivar"),
    path("dashboard/vehiculos/", vehiculos, name="vehiculos"),
    path("dashboard/vehiculos/agregar", vehiculos_agregar, name="vehiculos_agregar"),
    path("dashboard/vehiculos/detalles/<int:id>/", vehiculos_detalles, name="vehiculos_detalles"),
    path("dashboard/vehiculos/eliminar/<int:id>/", vehiculos_eliminar, name="vehiculos_eliminar"),
    path("dashboard/vehiculos/editar/<int:id>/", vehiculos_editar, name="vehiculos_editar"),
    path("dashboard/estadisticos/", estadisticos, name="estadisticos"),
    path("dashboard/control/", dashboard_control, name="dashboard_control"),
    path("dashboard/reportes/", reportes, name="reportes"),
    path("dashboard/perfil/", perfil, name="perfil"),
    path("buscar-persona/", buscar_persona_por_cedula, name="buscar_persona"),
    path('persona/<int:persona_id>/export_pdf/', exportar_historial_pdf, name='exportar_pdf'),
    path('vehiculos/<int:vehiculo_id>/export_pdf/', exportar_historial_pdf_vehiculos, name='exportar_pdf_vehiculo'),
    path('persona/<int:persona_id>/export_excel/', exportar_historial_excel, name='exportar_excel'),
    path('vehiculos/<int:vehiculo_id>/export_excel/', exportar_historial_excel_vehiculos, name='exportar_excel_vehiculo'),
    path("reportes/pdf/", exportar_pdf, name="exportar_pdf"),
    path('db-download/', db_download, name='db_download'),
    path('db-restore/', db_restore, name='db_restore'),
    path('db-panel/', db_panel, name='db_panel'),
]

modelNewProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("modelNewApp.urls")),

    #path("", HomeView.as_view(), name="home"),

    #path("modelNewApp/", include("modelNewApp.urls", namespace="modelNewApp")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/partials/personas_list.html
{% for empleado in empleados %}
<tr class="clickable-row" data-href="{% if empleado.id == request.user.persona.id %}{% url 'modelNewApp:perfil' %}{% else %}{% url 'modelNewApp:empleados_detalles' empleado.id %}{% endif %}">
    <td>{{ empleado.nombres }} {{ empleado.apellidos }}</td>
    <td>{{ empleado.fecha_registro|date:"d/m/Y" }}</td>
    <td>{% if empleado.codigo_p00%}{{ empleado.codigo_p00 }}{% else %}-{% endif %}</td>
    <td>
        <div class="{% if empleado.activo %}personaActiva{% else %}personaInactiva{% endif %}">{% if empleado.activo %}Activo{% else %}Inactivo{% endif %}
        </div>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="4">No se encontraron resultados</td>
</tr>
{% endfor %}

templates/partials/vehiculos_list.html
{% for vehiculo in vehiculos %}
<tr class="clickable-row" data-href="{% url 'modelNewApp:vehiculos_detalles' vehiculo.id %}">
    <td>{{ vehiculo.placa }}</td>
    <td>{{ vehiculo.marca.nombre }}</td>
    <td>{{ vehiculo.modelo.nombre }}</td>
    <td>{{ vehiculo.codigo }}</td>
</tr>
{% empty %}
<tr>
    <td colspan="4">No se encontraron resultados</td>
</tr>
{% endfor %}