modelNewApp/urls.py
from django.urls import path
from .views import *

app_name = "modelNewApp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("recuperar_contraseña/", recuperar_contraseña, name="recuperar_contraseña"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('cambiar_password/', cambiar_password, name='cambiar_password'),
    path("control/", control, name="control"),
    path("control/pie", control_pie, name="control_pie"),
    path("control/vehiculo", control_vehiculo, name="control_vehiculo"),
    path("ajax/buscar-vehiculo/", buscar_vehiculo_por_placa, name="buscar_vehiculo"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/personas/", empleados, name="empleados"),
    path("dashboard/personas/agregar", empleados_agregar, name="empleados_agregar"),
    path("dashboard/personas/detalles/<int:id>/", empleados_detalles, name="empleados_detalles"),
    path("dashboard/personas/eliminar/<int:id>/", empleados_eliminar, name="empleados_eliminar"),
    path("dashboard/personas/editar/<int:id>/", empleados_editar, name="empleados_editar"),
    path("dashboard/personas/activar/<int:id>/", empleados_activar, name="empleados_activar"),
    path("dashboard/personas/desactivar/<int:id>/", empleados_desactivar, name="empleados_desactivar"),
    path("dashboard/vehiculos/", vehiculos, name="vehiculos"),
    path("dashboard/vehiculos/agregar", vehiculos_agregar, name="vehiculos_agregar"),
    path("dashboard/vehiculos/detalles/<int:id>/", vehiculos_detalles, name="vehiculos_detalles"),
    path("dashboard/vehiculos/eliminar/<int:id>/", vehiculos_eliminar, name="vehiculos_eliminar"),
    path("dashboard/vehiculos/editar/<int:id>/", vehiculos_editar, name="vehiculos_editar"),
    path("dashboard/estadisticos/", estadisticos, name="estadisticos"),
    path("dashboard/control/", dashboard_control, name="dashboard_control"),
    path("dashboard/reportes/", reportes, name="reportes"),
    path("dashboard/perfil/", perfil, name="perfil"),
    path("buscar-persona/", buscar_persona_por_cedula, name="buscar_persona"),
    path('persona/<int:persona_id>/export_pdf/', exportar_historial_pdf, name='exportar_pdf'),
    path('vehiculos/<int:vehiculo_id>/export_pdf/', exportar_historial_pdf_vehiculos, name='exportar_pdf_vehiculo'),
    path('persona/<int:persona_id>/export_excel/', exportar_historial_excel, name='exportar_excel'),
    path('vehiculos/<int:vehiculo_id>/export_excel/', exportar_historial_excel_vehiculos, name='exportar_excel_vehiculo'),
    path("reportes/pdf/", exportar_pdf, name="exportar_pdf"),
    path('db-download/', db_download, name='db_download'),
    path('db-restore/', db_restore, name='db_restore'),
    path('db-panel/', db_panel, name='db_panel'),
]

modelNewProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("modelNewApp.urls")),

    #path("", HomeView.as_view(), name="home"),

    #path("modelNewApp/", include("modelNewApp.urls", namespace="modelNewApp")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/admin_db_panel.html
{% extends "pages/dashboard.html" %}
{% load static %}

{% block dashboard_content %}

<h1>Respaldo de Base de Datos</h1>

<h2>Descargar Base Actual</h2>
<a href="{% url 'modelNewApp:db_download' %}">
    <button>Descargar Base de Datos</button>
</a>

<hr>

<h2>Restaurar Base de Datos</h2>
<form method="post" action="{% url 'modelNewApp:db_restore' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="db_file" accept=".sqlite3" required>
    <button type="submit">Restaurar Base</button>
</form>

{% endblock %}

templates/pages/dashboard_control.html
{% extends "pages/dashboard.html" %}
{% load static %}

{% block dashboard_content %}

<div>Control</div>

{% endblock dashboard_content %}

templates/pages/empleados.html
{% extends "pages/dashboard.html" %}
{% load static %}
{% load querystring %}

{% block dashboard_content %}

<div class="d-flex justify-content-between align-items-center">
    <div class="sectionTitle">Personas</div>
    <a class="agregarEmpleadoLink" href="{% url 'modelNewApp:empleados_agregar' %}">
        <div class="agregarEmpleado">
            <img class="plusIcon" src="{% static 'images/plus icon.svg' %}" alt="Agregar empleado">
            <div class="">Agregar persona</div>
        </div>
    </a>
</div>
<div class="filterOptions">
    <div class="searchBar">
        <div class="input-group">
            <span class="input-group-text bg-white">
                <img src="{% static 'images/search icon.svg' %}" alt="Buscar" style="height:16px;">
            </span>
            <input
                    type="search"
                    name="search"
                    id="search-input"
                    class="form-control"
                    placeholder="Buscar..."
            >
        </div>
    </div>
    <form method="get" class="filtros d-flex gap-2 align-items-center">

    <!-- Tipo -->
    <select name="tipo" class="form-select w-auto" onchange="this.form.submit()">
        <option value="">Todos los tipos</option>
        {% for tipo in tipos %}
        <option value="{{ tipo.id }}"
            {% if request.GET.tipo == tipo.id|stringformat:"s" %}selected{% endif %}
        >
            {{ tipo.nombre_tipo }}
        </option>
        {% endfor %}
    </select>

    <!-- Estado -->
    <select name="estado" class="form-select w-auto" onchange="this.form.submit()">
        <option value="">Todos los estados</option>
        <option value="activo"
            {% if request.GET.estado == "activo" %}selected{% endif %}
        >
            Activo
        </option>
        <option value="inactivo"
            {% if request.GET.estado == "inactivo" %}selected{% endif %}
        >
            Inactivo
        </option>
    </select>

    <!-- Limpiar -->
    <a href="{% url 'modelNewApp:empleados' %}" class="btn btn-outline-secondary">
        Limpiar filtros
    </a>

</form>

</div>
<table class="table table-hover mt-3">
    <thead>
    <tr>
        <th>
            Nombre y apellido
            <a href="?{% if orden_actual == 'nombre' %}{% querystring request.GET 'orden' '-nombre' %}{% else %}{% querystring request.GET 'orden' 'nombre' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'nombre' %}asc{% elif orden_actual == '-nombre' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Fecha de registro
            <a href="?{% if orden_actual == 'fecha' %}{% querystring request.GET 'orden' '-fecha' %}{% else %}{% querystring request.GET 'orden' 'fecha' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'fecha' %}asc{% elif orden_actual == '-fecha' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Código P00
            <a href="?{% if orden_actual == 'codigo' %}{% querystring request.GET 'orden' '-codigo' %}{% else %}{% querystring request.GET 'orden' 'codigo' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'codigo' %}asc{% elif orden_actual == '-codigo' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Estado
            <a href="?{% if orden_actual == 'estado' %}{% querystring request.GET 'orden' '-estado' %}{% else %}{% querystring request.GET 'orden' 'estado' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'estado' %}asc{% elif orden_actual == '-estado' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
    </tr>
    </thead>
    <tbody id="personas-table">
    {% include "partials/personas_list.html" %}
    </tbody>
</table>

{% endblock dashboard_content %}

templates/pages/empleados_editar.html
{% extends "pages/dashboard.html" %}
{% load static %}

{% block dashboard_content %}

<div class="d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
        <a href="{% if persona.id == request.user.persona.id %}{% url 'modelNewApp:perfil' %}{% else %}{% url 'modelNewApp:empleados_detalles' persona.id %}{% endif %}">
            <img class="arrow-left" src="{% static 'images/left-arrow-return.svg' %}" alt="Volver">
        </a>
        <div class="sectionTitle ms-2">Editar Persona</div>
    </div>
</div>

<div class="mt-5">
    <form class="formAgregarPersona" method="post" action="{% url 'modelNewApp:empleados_editar' persona.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="container-fluid">
            <div class="row">

                <!-- COLUMNA IZQUIERDA -->
                <div class="col-6">

                    <!-- FOTO DE PERFIL -->
                    <div class="mb-4 p-3 border rounded">
                        <label class="form-label labelTitle">Foto de perfil</label>

                        {% if persona.foto_perfil %}
                        <div class="mb-2">
                            <img id="fotoPreview" src="{{ persona.foto_perfil.url }}" alt="Foto de {{ persona.nombres }}"
                                 class="img-thumbnail" style="max-width: 150px;">
                        </div>
                        {% else %}
                        <div class="mb-2">
                            <img id="fotoPreview" src="" alt="Foto de perfil" class="img-thumbnail" style="max-width: 150px; display: none;">
                        </div>
                        {% endif %}

                        <input
                            type="file"
                            name="foto_perfil"
                            class="form-control"
                            accept="image/*"
                            id="fotoInput"
                        >
                    </div>


                    <div class="mb-3">
                        <label class="form-label labelTitle">Nombres</label>
                        <input
                            name="nombres"
                            type="text"
                            class="form-control"
                            value="{% if data %}{{ data.nombres }}{% else %}{{ persona.nombres }}{% endif %}"
                            placeholder="Ingrese los nombres..."
                            required
                        >
                    </div>

                    <div class="mb-3">
                        <label class="form-label labelTitle">Apellidos</label>
                        <input
                            name="apellidos"
                            type="text"
                            class="form-control"
                            value="{% if data %}{{ data.apellidos }}{% else %}{{ persona.apellidos }}{% endif %}"
                            placeholder="Ingrese los apellidos..."
                            required
                        >
                    </div>

                    <div class="mb-3">
                        <label class="form-label labelTitle">Cédula</label>
                        <input
                            name="cedula"
                            type="text"
                            class="form-control"
                            value="{% if data %}{{ data.cedula }}{% else %}{{ persona.cedula }}{% endif %}"
                            placeholder="Ingrese el número de cédula..."
                            required
                        >
                    </div>

                    <div class="mb-3">
                        <label class="form-label labelTitle">Código P00</label>
                        <input
                            name="codigo"
                            type="text"
                            class="form-control"
                            value="{% if data %}{{ data.codigo }}{% else %}{{ persona.codigo_p00|default:'' }}{% endif %}"
                            placeholder="Ingrese el código P00..."
                            required
                        >
                    </div>

                    <!-- TIPO DE PERSONA -->
                    <div class="mb-3">
                        <label class="form-label labelTitle">Tipo de persona</label>

                        {% for tipo in tipos %}
                        <div class="form-check tipoPersonaRadio">
                            <input
                                class="form-check-input"
                                type="radio"
                                name="tipo_persona"
                                value="{{ tipo.id }}"
                                id="tipo_{{ tipo.id }}"
                                {% if data %}
                                    {% if data.tipo_persona == tipo.id|stringformat:"s" %}checked{% endif %}
                                {% else %}
                                    {% if persona.id_tipo.id == tipo.id %}checked{% endif %}
                                {% endif %}
                                required
                            >
                            <label class="form-check-label" for="tipo_{{ tipo.id }}">{{ tipo.nombre_tipo }}</label>
                        </div>
                        {% endfor %}
                    </div>

                    <!-- DEPARTAMENTO -->
                    <div class="mb-3">
                        <label for="departamento" class="form-label labelTitle">Departamento</label>
                        <select
                            name="departamento"
                            id="departamento"
                            class="form-select"
                        >
                            <option value="">Seleccione un departamento</option>

                            {% for departamento in departamentos %}
                                <option
                                    value="{{ departamento.id }}"
                                    {% if data %}
                                        {% if data.departamento|add:0 == departamento.id %}selected{% endif %}
                                    {% else %}
                                        {% if persona.departamento and persona.departamento.id == departamento.id %}selected{% endif %}
                                    {% endif %}
                                >
                                    {{ departamento.nombre }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>


                    <!-- SEXO -->
                    <div class="mb-3">
                        <label class="form-label labelTitle">Sexo</label>
                        <select name="sexo" class="form-select" required>
                            <option value="">Seleccione sexo</option>
                            <option value="M" {% if data and data.sexo == "M" or persona.sexo == "M" %}selected{% endif %}>Masculino</option>
                            <option value="F" {% if data and data.sexo == "F" or persona.sexo == "F" %}selected{% endif %}>Femenino</option>
                            <option value="O" {% if data and data.sexo == "O" or persona.sexo == "O" %}selected{% endif %}>Otro</option>
                        </select>
                    </div>

                    <!-- ADMIN -->
                    <div class="mb-3">
                        <div class="form-check">
                            <input
                                name="administrador"
                                class="form-check-input"
                                type="checkbox"
                                value="checked"
                                id="admin"
                                {% if data and data.administrador == "checked" or persona.empleado %}checked{% endif %}
                            >
                            <label class="form-check-label" for="admin">El empleado es un administrador</label>
                        </div>
                    </div>

                </div>

                <!-- COLUMNA DERECHA -->
                <div class="col-6">

                    <!-- EMAIL -->
                    <div class="mb-3">
                        <label class="form-label labelTitle">Correo electrónico</label>
                        <input
                            name="email"
                            type="email"
                            class="form-control"
                            value="{% if data %}{{data.email}}{% else %}{{persona.empleado.email}}{% endif %}"
                            placeholder="Ingrese correo electrónico..."
                            id="email"
                            required
                            {% if data %}{% if data.administrador %}{% else %}disabled{% endif %}{% else %}{% if persona.empleado %}{% else %}disabled{% endif %}{% endif %}
                        >
                        <small class="text-muted">
                            La contraseña será generada automáticamente si es nueva
                        </small>
                    </div>

                    <!-- ROLES -->
                    <div class="mb-3 p-3 border rounded">
                        <label class="form-label labelTitle">Roles</label>

                        {% for rol in roles %}
                        <div class="form-check">
                            <input
                                class="form-check-input role-checkbox"
                                type="checkbox"
                                name="roles"
                                value="{{ rol.id }}"
                                id="rol_{{ rol.id }}"
                                {% if rol.id in roles_persona %}checked{% endif %}
                                {% if data %}{% if data.administrador %}{% else %}disabled{% endif %}{% else %}{% if persona.empleado %}{% else %}disabled{% endif %}{% endif %}
                            >
                            <label class="form-check-label roles" for="rol_{{ rol.id }}">{{ rol.nombre_rol }}</label>
                        </div>
                        {% endfor %}
                    </div>

                </div>

            </div>

            <!-- MENSAJES -->
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger mt-3 alert-auto-close">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}

            <!-- BOTÓN -->
            <div class="row mt-4">
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary" type="submit">
                        Editar persona
                    </button>
                </div>
            </div>

        </div>
    </form>
</div>

{% endblock dashboard_content %}

templates/pages/vehiculos.html
{% extends "pages/dashboard.html" %}
{% load static %}
{% load querystring %}

{% block dashboard_content %}

<div class="d-flex justify-content-between align-items-center">
    <div class="sectionTitle">Vehiculos</div>
    <a class="agregarEmpleadoLink" href="{% url 'modelNewApp:vehiculos_agregar' %}">
        <div class="agregarEmpleado">
            <img class="plusIcon" src="{% static 'images/plus icon.svg' %}" alt="Agregar vehiculo">
            <div class="">Agregar vehiculo</div>
        </div>
    </a>
</div>
<div class="filterOptions">
    <div class="searchBar">
        <div class="input-group">
            <span class="input-group-text bg-white">
                <img src="{% static 'images/search icon.svg' %}" alt="Buscar" style="height:16px;">
            </span>
            <input
                    type="search"
                    name="search"
                    id="search-input-vehiculos"
                    class="form-control"
                    placeholder="Buscar..."
            >
        </div>
    </div>
    <form method="get" class="filtros d-flex gap-2 align-items-center">

    <!-- Marca -->
    <select name="marca" class="form-select w-auto" onchange="this.form.submit()">
        <option value="">Todas las marcas</option>
        {% for marca in marcas %}
        <option value="{{ marca.id }}"
            {% if request.GET.marca == marca.id|stringformat:"s" %}selected{% endif %}
        >
            {{ marca.nombre }}
        </option>
        {% endfor %}
    </select>

    <!-- Modelo -->
    <select name="modelo" class="form-select w-auto" onchange="this.form.submit()">
        <option value="">Todos los modelos</option>
        {% for modelo in modelos %}
        <option value="{{ modelo.id }}"
            {% if request.GET.modelo == modelo.id|stringformat:"s" %}selected{% endif %}
        >
            {{ modelo.nombre }}
        </option>
        {% endfor %}
    </select>

    <!-- Limpiar -->
    <a href="{% url 'modelNewApp:vehiculos' %}" class="btn btn-outline-secondary">
        Limpiar filtros
    </a>

</form>

</div>
<table class="table table-hover mt-3">
    <thead>
    <tr>
        <th>
            Placa
            <a href="?{% if orden_actual == 'placa' %}{% querystring request.GET 'orden' '-placa' %}{% else %}{% querystring request.GET 'orden' 'placa' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'placa' %}asc{% elif orden_actual == '-placa' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Marca
            <a href="?{% if orden_actual == 'marca' %}{% querystring request.GET 'orden' '-marca' %}{% else %}{% querystring request.GET 'orden' 'marca' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'marca' %}asc{% elif orden_actual == '-marca' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Modelo
            <a href="?{% if orden_actual == 'codigo' %}{% querystring request.GET 'orden' '-codigo' %}{% else %}{% querystring request.GET 'orden' 'codigo' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'codigo' %}asc{% elif orden_actual == '-codigo' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
        <th>
            Código
            <a href="?{% if orden_actual == 'estado' %}{% querystring request.GET 'orden' '-estado' %}{% else %}{% querystring request.GET 'orden' 'estado' %}{% endif %}"
               class="sort-icon
               {% if orden_actual == 'estado' %}asc{% elif orden_actual == '-estado' %}desc{% endif %}">
                <svg width="14" height="14" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="18 15 12 9 6 15"></polyline>
                </svg>
            </a>
        </th>
    </tr>
    </thead>
    <tbody id="vehiculos-table">
    {% include "partials/vehiculos_list.html" %}
    </tbody>
</table>

{% endblock dashboard_content %}

templates/pages/vehiculos_detalles.html
{% extends "pages/dashboard.html" %}
{% load static %}

{% block dashboard_content %}

<div class="d-flex justify-content-between align-items-center mb-4">
    <div class="d-flex align-items-center gap-3">

        <div class="d-flex align-items-center">
            <a class="" href="{% url 'modelNewApp:vehiculos' %}">
                <img class="arrow-left" src="{% static 'images/left-arrow-return.svg' %}" alt="">
            </a>
            <div class="sectionTitle">Vehículo</div>
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown">
            Acciones
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
            <li>
                <a class="dropdown-item" href="{% url 'modelNewApp:vehiculos_editar' vehiculo.id %}">
                    Editar
                </a>
            </li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li>
                <button class="dropdown-item text-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#borrarVehiculo">
                    Eliminar
                </button>
            </li>
        </ul>
    </div>


</div>

<div class="card mb-4">
    <div class="card-body">
        <h5 class="mb-3">Información del vehículo</h5>

        <div class="row">
            <div class="col-md-6">
                <p><strong>Placa:</strong> {{ vehiculo.placa|upper }}</p>
                <p><strong>Marca:</strong> {{ vehiculo.marca.nombre|title }} </p>
                <p><strong>Modelo:</strong> {{ vehiculo.modelo.nombre|title }} </p>
                {% if vehiculo.codigo %}
                    <p><strong>Código:</strong> {{ vehiculo.codigo|title }} </p>
                {% endif %}
            </div>

            <div class="col-md-6">

            </div>
        </div>
    </div>
</div>

<!-- Modal eliminar -->
<div class="modal fade" id="borrarVehiculo" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="borrarVehiculoLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="borrarVehiculoLabel">Eliminar vehículo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Estás seguro que quieres eliminar el vehículo con placa {{ vehiculo.placa }}?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'modelNewApp:vehiculos_eliminar' vehiculo.id %}">Aceptar</a>
            </div>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body">

        <div class="d-flex justify-content-between align-items-center mb-2">
            <div>
                <h5 class="mb-0">Historial de accesos</h5>
                Mostrando resultados: {{ page_obj.start_index }} a {{ page_obj.end_index }} de {{ page_obj.paginator.count }}
            </div>

            <div class="btn-group">
                <a href="{% url 'modelNewApp:exportar_pdf_vehiculo' vehiculo.id %}" class="btn btn-danger">
                    PDF
                </a>
                <a href="{% url 'modelNewApp:exportar_excel_vehiculo' vehiculo.id %}" class="btn btn-success">
                    Excel
                </a>
            </div>
        </div>


        <div class="table-responsive" style="">
            <table class="table table-hover align-middle">
                <thead>
                <tr>
                    <th>Fecha y hora</th>
                    <th>Movimiento</th>
                    <th>Departamento</th>
                </tr>
                </thead>
                <tbody>
                {% for acceso in page_obj %}
                <tr>
                    <td>{{ acceso.fecha_hora|date:"d/m/Y h:i A" }}</td>
                    <td>
                        {% if acceso.tipo_movimiento == "INGRESO" %}
                        <span class="badge bg-success">
                            <i class="bi bi-box-arrow-in-right"></i> Ingreso
                        </span>

                        {% else %}
                        <span class="badge bg-danger">
                            <i class="bi bi-box-arrow-left"></i> Salida
                        </span>

                        {% endif %}
                    </td>
                    <td>{% if acceso.departamento_destino %}{{ acceso.departamento_destino.nombre }}{% else %}—{% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3" class="text-center text-muted">No hay registros de acceso para esta persona</td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>

    </div>
</div>


<div class="d-flex justify-content-center mt-3">
    <nav aria-label="Historial de accesos">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            </li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Anterior</span></li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
            {% elif num >= page_obj.number|add:'-2' and num <= page_obj.number|add:'2' %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            </li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Siguiente</span></li>
            {% endif %}
        </ul>
    </nav>
</div>


{% endblock dashboard_content %}