modelNewApp/urls.py
from django.urls import path
from .views import *

app_name = "modelNewApp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("recuperar_contraseña/", recuperar_contraseña, name="recuperar_contraseña"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path('cambiar_password/', cambiar_password, name='cambiar_password'),
    path("control/", control, name="control"),
    path("control/pie", control_pie, name="control_pie"),
    path("control/vehiculo", control_vehiculo, name="control_vehiculo"),
    path("ajax/buscar-vehiculo/", buscar_vehiculo_por_placa, name="buscar_vehiculo"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/personas/", empleados, name="empleados"),
    path("dashboard/personas/agregar", empleados_agregar, name="empleados_agregar"),
    path("dashboard/personas/detalles/<int:id>/", empleados_detalles, name="empleados_detalles"),
    path("dashboard/personas/eliminar/<int:id>/", empleados_eliminar, name="empleados_eliminar"),
    path("dashboard/personas/editar/<int:id>/", empleados_editar, name="empleados_editar"),
    path("dashboard/personas/activar/<int:id>/", empleados_activar, name="empleados_activar"),
    path("dashboard/personas/desactivar/<int:id>/", empleados_desactivar, name="empleados_desactivar"),
    path("dashboard/vehiculos/", vehiculos, name="vehiculos"),
    path("dashboard/vehiculos/agregar", vehiculos_agregar, name="vehiculos_agregar"),
    path("dashboard/vehiculos/detalles/<int:id>/", vehiculos_detalles, name="vehiculos_detalles"),
    path("dashboard/vehiculos/eliminar/<int:id>/", vehiculos_eliminar, name="vehiculos_eliminar"),
    path("dashboard/vehiculos/editar/<int:id>/", vehiculos_editar, name="vehiculos_editar"),
    path("dashboard/estadisticos/", estadisticos, name="estadisticos"),
    path("dashboard/control/", dashboard_control, name="dashboard_control"),
    path("dashboard/reportes/", reportes, name="reportes"),
    path("dashboard/perfil/", perfil, name="perfil"),
    path("buscar-persona/", buscar_persona_por_cedula, name="buscar_persona"),
    path('persona/<int:persona_id>/export_pdf/', exportar_historial_pdf, name='exportar_pdf'),
    path('vehiculos/<int:vehiculo_id>/export_pdf/', exportar_historial_pdf_vehiculos, name='exportar_pdf_vehiculo'),
    path('persona/<int:persona_id>/export_excel/', exportar_historial_excel, name='exportar_excel'),
    path('vehiculos/<int:vehiculo_id>/export_excel/', exportar_historial_excel_vehiculos, name='exportar_excel_vehiculo'),
    path("reportes/pdf/", exportar_pdf, name="exportar_pdf"),
    path('db-download/', db_download, name='db_download'),
    path('db-restore/', db_restore, name='db_restore'),
    path('db-panel/', db_panel, name='db_panel'),
]

modelNewProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("modelNewApp.urls")),

    #path("", HomeView.as_view(), name="home"),

    #path("modelNewApp/", include("modelNewApp.urls", namespace="modelNewApp")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/footer.html
{% load static %}

<div class="footer d-flex align-items-center">
    <img class="logoRight" src="{% static 'images/mincyt.png' %}" alt="Info">
    <img class="logoLeft" src="{% static 'images/Cantv-1-colores.png' %}" alt="Logo">
</div>

templates/components/navbar.html
{% load static %}

<div class="superior">
    <div class="nav-left">
        <a href="{% url 'modelNewApp:control' %}">
            <img class="logoNav" src="{% static 'images/cantv-white.png' %}" alt="Cantv logo">
        </a>
    </div>

    {% if user.is_authenticated %}
    <div class="dropdown profileMenu">
        <div class="nav-right dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.email }}  <!-- o user.get_full_name si lo defines -->
            <div class="thumbnail-content">
                {% if user.persona.foto_perfil %}
                    <div class="">
                        <img class="thumbnail-content" src="{{ user.persona.foto_perfil.url }}" width="45">
                    </div>
                {% else %}
                    <div class="">
                        <img class="thumbnail-content" src="{% static 'images/profile_empty.jpg' %}" width="45">
                    </div>
                {% endif %}
        </div>
    </div>
        <ul class="dropdown-menu">
            {% if request.path|slice:":10" == '/dashboard' %}
                <li><a class="dropdown-item" href="{% url 'modelNewApp:control' %}">Control</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'modelNewApp:dashboard' %}">Dashboard</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'modelNewApp:logout' %}">Cerrar sesión</a></li>
        </ul>
    </div>
    {% endif %}

</div>

templates/components/sidebar.html
{% load static %}
<!-- Sidebar -->
<nav class="sidebar col-md-3 col-lg-2 text-white sidebar-col">
    <ul class="nav flex-column">
        <li class="nav-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}"><a class="nav-link {% if request.resolver_match.url_name == 'dashboard' %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:dashboard' %}">
            <svg class="dashboardIcon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <rect x="3" y="3" width="7" height="9"></rect>
              <rect x="14" y="3" width="7" height="5"></rect>
              <rect x="14" y="12" width="7" height="9"></rect>
              <rect x="3" y="16" width="7" height="5"></rect>
            </svg>
            <span class="ms-2 span-sidebar">Dashboard</span></a>
        </li>
        <li class="nav-item {% if '/dashboard/personas/' in request.path %}active{% endif %}"><a class="nav-link {% if '/dashboard/personas/' in request.path %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:empleados' %}"><img class="dashboardIcon" src="{% if '/dashboard/personas/' in request.path %}{% static 'images/users icon white.svg' %}{% else %}{% static 'images/users icon.svg' %}{% endif %}" alt=""><span class="ms-2 span-sidebar">Personas</span></a></li>
        <li class="nav-item {% if '/dashboard/vehiculos/' in request.path %}active{% endif %}"><a class="nav-link {% if '/dashboard/vehiculos/' in request.path %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:vehiculos' %}"><img class="dashboardIcon" src="{% if '/dashboard/vehiculos/' in request.path %}{% static 'images/users icon white.svg' %}{% else %}{% static 'images/users icon.svg' %}{% endif %}" alt=""><span class="ms-2 span-sidebar">Vehiculos</span></a></li>
        {% if es_admin or user.is_superuser %}
        <li class="nav-item {% if '/dashboard/estadisticos/' in request.path %}active{% endif %}"><a class="nav-link {% if '/dashboard/estadisticos/' in request.path %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:estadisticos' %}"><img class="dashboardIcon" src="{% if '/dashboard/estadisticos/' in request.path %}{% static 'images/dashboard icon white.svg' %}{% else %}{% static 'images/dashboard icon.svg' %}{% endif %}" alt=""><span class="ms-2 span-sidebar">Estadísticos</span></a></li>
        {% else %}
        {% endif %}
        {% if es_admin or user.is_superuser %}
        <li class="nav-item {% if '/dashboard/reportes/' in request.path %}active{% endif %}"><a class="nav-link {% if '/dashboard/reportes/' in request.path %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:reportes' %}">
            <svg class="dashboardIcon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
              <polyline points="14 2 14 8 20 8"></polyline>
              <line x1="16" y1="13" x2="8" y2="13"></line>
              <line x1="16" y1="17" x2="8" y2="17"></line>
            </svg>
            <span class="ms-2 span-sidebar">Reportes</span></a>
        </li>
        {% else %}
        {% endif %}

        {% if user.persona %}
            {% if user.persona == "None" %}
            {% else %}
            <li class="nav-item {% if '/dashboard/perfil/' in request.path %}active{% endif %}"><a class="nav-link {% if '/dashboard/perfil/' in request.path %}text-white{% else %}text-black{% endif %} d-flex align-items-center pt-4 pb-4" href="{% url 'modelNewApp:perfil' %}"><img class="dashboardIcon" src="{% if '/dashboard/perfil/' in request.path %}{% static 'images/perfil icon white.svg' %}{% else %}{% static 'images/perfil icon.svg' %}{% endif %}" alt=""><span class="ms-2 span-sidebar">Perfil</span></a></li>
            {% endif %}
        {% else %}
        {% endif %}
    </ul>
</nav>